2012-10-05 00:30:00,037 ERROR [EJBVelocity] (Thread-16926) ::nobody::1962: ResourceManager : unable to find resource '/email/email_cust_deposit_release_en.vm' in any resource loader.
2012-10-05 00:30:00,037 ERROR [com.riavera.app.service.template.WTemplate] (Thread-16926) ::nobody::1962: cannot locate template '/email/email_cust_deposit_release_en.vm' - velocity exception: Unable to find resource '/email/email_cust_deposit_release_en.vm'
2012-10-05 00:30:00,038 ERROR [com.riavera.ejb.session.EventDispatcherBean] (Thread-16926) ::nobody::1962: exception handling queued event 21CB48F6C0A81447395C2C99A7C11390 - will retry again later: com.riavera.exceptions.WNotFoundException: TEMPLATE_NOT_FOUND (9501): Cannot locate template
	at com.riavera.app.service.template.WTemplate.processTemplateToFile(WTemplate.java:358) [:]
	at sun.reflect.GeneratedMethodAccessor4552.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:157) [:6.0.0.GA]
	at org.jboss.mx.server.Invocation.dispatch(Invocation.java:96) [:6.0.0.GA]
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:88) [:6.0.0.GA]
2012-10-05 04:55:00,039 ERROR [com.riavera.ejb.session.EventDispatcherBean] (Thread-16925) ::nobody::2003: unexpected exception processing callback for event 0904C523C0A81447668E37B60976341C: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [:1.6.0_33]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at com.riavera.ejb.session.EventDispatcherBean.finishAttempt(EventDispatcherBean.java:438) [:]
	at sun.reflect.GeneratedMethodAccessor4196.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
2012-10-05 07:16:28,552 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#5[192.168.20.71:46720]) :MobileWallet:127.0.0.1:nnapp_fi_in::::0:  unable to find cust user:madridfjNo such entity!
2012-10-05 09:00:08,342 ERROR [org.jboss.ejb.plugins.LogInterceptor] (WorkerThread#0[192.168.20.71:9802])  TransactionRolledbackException in method: public abstract javax.ejb.EJBObject javax.ejb.Handle.getEJBObject() throws java.rmi.RemoteException, causedBy:: java.rmi.NoSuchObjectException: Could not activate; failed to restore state
	at org.jboss.ejb.plugins.AbstractInstanceCache.get(AbstractInstanceCache.java:134) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer.getEJBObject(StatefulSessionContainer.java:394) [:6.1.0.Final]
	at sun.reflect.GeneratedMethodAccessor3683.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at org.jboss.invocation.Invocation.performCall(Invocation.java:386) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer$ContainerInterceptor.invokeHome(StatefulSessionContainer.java:564) [:6.1.0.Final]
2012-10-05 09:00:08,351 ERROR [org.jboss.ejb.plugins.LogInterceptor] (WorkerThread#0[192.168.20.71:9802])  TransactionRolledbackException in method: public abstract javax.ejb.EJBObject javax.ejb.Handle.getEJBObject() throws java.rmi.RemoteException, causedBy:: java.rmi.NoSuchObjectException: Could not activate; failed to restore state
	at org.jboss.ejb.plugins.AbstractInstanceCache.get(AbstractInstanceCache.java:134) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer.getEJBObject(StatefulSessionContainer.java:394) [:6.1.0.Final]
	at sun.reflect.GeneratedMethodAccessor3683.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at org.jboss.invocation.Invocation.performCall(Invocation.java:386) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer$ContainerInterceptor.invokeHome(StatefulSessionContainer.java:564) [:6.1.0.Final]
2012-10-05 12:20:00,039 ERROR [com.riavera.ejb.session.EventDispatcherBean] (Thread-16926) ::nobody::2052: unexpected exception processing callback for event 0FC6BF8FC0A8144703FD6DB5F3A949F2: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [:1.6.0_33]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at com.riavera.ejb.session.EventDispatcherBean.finishAttempt(EventDispatcherBean.java:438) [:]
	at sun.reflect.GeneratedMethodAccessor4196.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
2012-10-05 12:20:00,069 ERROR [com.riavera.ejb.session.EventDispatcherBean] (Thread-16926) ::nobody::2054: unexpected exception processing callback for event 0FC7BBF7C0A8144723A1E52CD6BC302E: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [:1.6.0_33]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at com.riavera.ejb.session.EventDispatcherBean.finishAttempt(EventDispatcherBean.java:438) [:]
	at sun.reflect.GeneratedMethodAccessor4196.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
2012-10-05 12:40:00,103 ERROR [EJBVelocity] (Thread-16925) ::nobody::2059: ResourceManager : unable to find resource '/email/email_cust_deposit_release_en.vm' in any resource loader.
2012-10-05 12:40:00,103 ERROR [com.riavera.app.service.template.WTemplate] (Thread-16925) ::nobody::2059: cannot locate template '/email/email_cust_deposit_release_en.vm' - velocity exception: Unable to find resource '/email/email_cust_deposit_release_en.vm'
2012-10-05 12:40:00,104 ERROR [com.riavera.ejb.session.EventDispatcherBean] (Thread-16925) ::nobody::2059: exception handling queued event 26F1A54BC0A8144712588D7A6DF90AC9 - will retry again later: com.riavera.exceptions.WNotFoundException: TEMPLATE_NOT_FOUND (9501): Cannot locate template
	at com.riavera.app.service.template.WTemplate.processTemplateToFile(WTemplate.java:358) [:]
	at sun.reflect.GeneratedMethodAccessor4552.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:157) [:6.0.0.GA]
	at org.jboss.mx.server.Invocation.dispatch(Invocation.java:96) [:6.0.0.GA]
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:88) [:6.0.0.GA]
2012-10-05 13:39:19,933 ERROR [org.jboss.ejb.plugins.LogInterceptor] (WorkerThread#3[192.168.20.71:54338])  TransactionRolledbackException in method: public abstract javax.ejb.EJBObject javax.ejb.Handle.getEJBObject() throws java.rmi.RemoteException, causedBy:: java.rmi.NoSuchObjectException: Could not activate; failed to restore state
	at org.jboss.ejb.plugins.AbstractInstanceCache.get(AbstractInstanceCache.java:134) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer.getEJBObject(StatefulSessionContainer.java:394) [:6.1.0.Final]
	at sun.reflect.GeneratedMethodAccessor3683.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at org.jboss.invocation.Invocation.performCall(Invocation.java:386) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer$ContainerInterceptor.invokeHome(StatefulSessionContainer.java:564) [:6.1.0.Final]
2012-10-05 13:45:00,043 ERROR [com.riavera.ejb.session.EventDispatcherBean] (Thread-16926) ::nobody::2078: unexpected exception processing callback for event 05BC3DD2C0A814470711AADCF24E35C4: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [:1.6.0_33]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at com.riavera.ejb.session.EventDispatcherBean.finishAttempt(EventDispatcherBean.java:438) [:]
	at sun.reflect.GeneratedMethodAccessor4196.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
2012-10-05 13:45:00,126 ERROR [com.riavera.ejb.session.EventDispatcherBean] (Thread-16926) ::nobody::2080: unexpected exception processing callback for event 05BDDE01C0A814472B73D6417B0E428B: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [:1.6.0_33]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at com.riavera.ejb.session.EventDispatcherBean.finishAttempt(EventDispatcherBean.java:438) [:]
	at sun.reflect.GeneratedMethodAccessor4196.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
2012-10-05 14:31:45,962 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#5[192.168.20.71:12428]) :MIISCAN:127.0.0.1:coyoli79::M4H1J6::0:  unable to find cust user:coyoli79No such entity!
2012-10-05 14:34:26,890 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#0[192.168.20.71:12434]) :MIISCAN:127.0.0.1:coyoli79::M4H1J6::0:  unable to find cust user:coyoli79No such entity!
2012-10-05 14:39:20,979 ERROR [org.jboss.ejb.plugins.LogInterceptor] (WorkerThread#3[192.168.20.71:12420])  TransactionRolledbackException in method: public abstract javax.ejb.EJBObject javax.ejb.Handle.getEJBObject() throws java.rmi.RemoteException, causedBy:: java.rmi.NoSuchObjectException: Could not activate; failed to restore state
	at org.jboss.ejb.plugins.AbstractInstanceCache.get(AbstractInstanceCache.java:134) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer.getEJBObject(StatefulSessionContainer.java:394) [:6.1.0.Final]
	at sun.reflect.GeneratedMethodAccessor3683.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at org.jboss.invocation.Invocation.performCall(Invocation.java:386) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer$ContainerInterceptor.invokeHome(StatefulSessionContainer.java:564) [:6.1.0.Final]
2012-10-05 14:39:20,988 ERROR [org.jboss.ejb.plugins.LogInterceptor] (WorkerThread#3[192.168.20.71:12420])  TransactionRolledbackException in method: public abstract javax.ejb.EJBObject javax.ejb.Handle.getEJBObject() throws java.rmi.RemoteException, causedBy:: java.rmi.NoSuchObjectException: Could not activate; failed to restore state
	at org.jboss.ejb.plugins.AbstractInstanceCache.get(AbstractInstanceCache.java:134) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer.getEJBObject(StatefulSessionContainer.java:394) [:6.1.0.Final]
	at sun.reflect.GeneratedMethodAccessor3683.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at org.jboss.invocation.Invocation.performCall(Invocation.java:386) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer$ContainerInterceptor.invokeHome(StatefulSessionContainer.java:564) [:6.1.0.Final]
012-10-05 15:37:33,743 ERROR [org.jboss.ejb.plugins.LogInterceptor] (WorkerThread#3[192.168.20.71:16892])  TransactionRolledbackException in method: public abstract javax.ejb.EJBObject javax.ejb.Handle.getEJBObject() throws java.rmi.RemoteException, causedBy:: java.rmi.NoSuchObjectException: Could not activate; failed to restore state
	at org.jboss.ejb.plugins.AbstractInstanceCache.get(AbstractInstanceCache.java:134) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer.getEJBObject(StatefulSessionContainer.java:394) [:6.1.0.Final]
	at sun.reflect.GeneratedMethodAccessor3683.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at org.jboss.invocation.Invocation.performCall(Invocation.java:386) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer$ContainerInterceptor.invokeHome(StatefulSessionContainer.java:564) [:6.1.0.Final]
2012-10-05 15:37:33,802 ERROR [org.jboss.ejb.plugins.LogInterceptor] (WorkerThread#3[192.168.20.71:16892])  TransactionRolledbackException in method: public abstract javax.ejb.EJBObject javax.ejb.Handle.getEJBObject() throws java.rmi.RemoteException, causedBy:: java.rmi.NoSuchObjectException: Could not activate; failed to restore state
	at org.jboss.ejb.plugins.AbstractInstanceCache.get(AbstractInstanceCache.java:134) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer.getEJBObject(StatefulSessionContainer.java:394) [:6.1.0.Final]
	at sun.reflect.GeneratedMethodAccessor3683.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at org.jboss.invocation.Invocation.performCall(Invocation.java:386) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer$ContainerInterceptor.invokeHome(StatefulSessionContainer.java:564) [:6.1.0.Final]
2012-10-05 15:37:33,820 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#3[192.168.20.71:16892])  bad: HOME_NAME_PREFIX 
2012-10-05 15:37:33,820 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#3[192.168.20.71:16892])  invalidDataMap: {OPERATIONAL_PASSWORD=1004, HOME_NAME_PREFIX=45001, HOME_PHONE=45016}
2012-10-05 15:38:42,203 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#5[192.168.20.71:16894])  bad: 
2012-10-05 15:38:42,203 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#5[192.168.20.71:16894])  invalidDataMap: {OPERATIONAL_PASSWORD=1004}
2012-10-05 15:41:35,658 ERROR [org.jboss.ejb.plugins.LogInterceptor] (WorkerThread#0[192.168.20.71:64804])  TransactionRolledbackException in method: public abstract javax.ejb.EJBObject javax.ejb.Handle.getEJBObject() throws java.rmi.RemoteException, causedBy:: java.rmi.NoSuchObjectException: Could not activate; failed to restore state
	at org.jboss.ejb.plugins.AbstractInstanceCache.get(AbstractInstanceCache.java:134) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer.getEJBObject(StatefulSessionContainer.java:394) [:6.1.0.Final]
	at sun.reflect.GeneratedMethodAccessor3683.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at org.jboss.invocation.Invocation.performCall(Invocation.java:386) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer$ContainerInterceptor.invokeHome(StatefulSessionContainer.java:564) [:6.1.0.Final]
2012-10-05 15:41:35,667 ERROR [org.jboss.ejb.plugins.LogInterceptor] (WorkerThread#0[192.168.20.71:64804])  TransactionRolledbackException in method: public abstract javax.ejb.EJBObject javax.ejb.Handle.getEJBObject() throws java.rmi.RemoteException, causedBy:: java.rmi.NoSuchObjectException: Could not activate; failed to restore state
	at org.jboss.ejb.plugins.AbstractInstanceCache.get(AbstractInstanceCache.java:134) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer.getEJBObject(StatefulSessionContainer.java:394) [:6.1.0.Final]
	at sun.reflect.GeneratedMethodAccessor3683.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at org.jboss.invocation.Invocation.performCall(Invocation.java:386) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer$ContainerInterceptor.invokeHome(StatefulSessionContainer.java:564) [:6.1.0.Final]
2012-10-05 16:08:17,870 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#0[192.168.20.71:32642])  bad: 
2012-10-05 16:08:17,871 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#0[192.168.20.71:32642])  invalidDataMap: {OPERATIONAL_LOGIN=1015}
2012-10-05 16:45:15,187 INFO  [com.riavera.ejb.session.MerchantApiBean] (WorkerThread#4[192.168.20.71:54309])  query-cust-coupons API request failed for merchant: merchantId=100000060309, custGuid=63d2d9b025dcb6d8afeb12361369712b - err=CUST_NOT_EXIST (30001)
2012-10-05 16:45:15,846 INFO  [com.riavera.ejb.session.MerchantApiBean] (WorkerThread#1[192.168.20.71:54311])  query-cust-coupons API request failed for merchant: merchantId=100000060309, custGuid=63d2d9b025dcb6d8afeb12361369712b - err=CUST_NOT_EXIST (30001)
2012-10-05 16:45:22,318 ERROR [org.jboss.ejb.plugins.LogInterceptor] (WorkerThread#5[192.168.20.71:31208])  TransactionRolledbackException in method: public abstract javax.ejb.EJBObject javax.ejb.Handle.getEJBObject() throws java.rmi.RemoteException, causedBy:: java.rmi.NoSuchObjectException: Could not activate; failed to restore state
	at org.jboss.ejb.plugins.AbstractInstanceCache.get(AbstractInstanceCache.java:134) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer.getEJBObject(StatefulSessionContainer.java:394) [:6.1.0.Final]
	at sun.reflect.GeneratedMethodAccessor3683.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at org.jboss.invocation.Invocation.performCall(Invocation.java:386) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer$ContainerInterceptor.invokeHome(StatefulSessionContainer.java:564) [:6.1.0.Final]
2012-10-05 16:45:25,546 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#5[192.168.20.71:31208])  no service_config parameter wallet_bal_min_CAD defined!
2012-10-05 16:46:54,082 ERROR [org.jboss.ejb.plugins.LogInterceptor] (WorkerThread#0[192.168.20.71:39422])  TransactionRolledbackException in method: public abstract javax.ejb.EJBObject javax.ejb.Handle.getEJBObject() throws java.rmi.RemoteException, causedBy:: java.rmi.NoSuchObjectException: Could not activate; failed to restore state
	at org.jboss.ejb.plugins.AbstractInstanceCache.get(AbstractInstanceCache.java:134) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer.getEJBObject(StatefulSessionContainer.java:394) [:6.1.0.Final]
	at sun.reflect.GeneratedMethodAccessor3683.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at org.jboss.invocation.Invocation.performCall(Invocation.java:386) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer$ContainerInterceptor.invokeHome(StatefulSessionContainer.java:564) [:6.1.0.Final]
2012-10-05 16:46:54,111 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#0[192.168.20.71:39422])  bad: 
2012-10-05 16:46:54,111 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#0[192.168.20.71:39422])  invalidDataMap: {HOME_PHONE=45016}
2012-10-05 16:56:31,662 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#3[192.168.20.71:30356])  no service_config parameter wallet_bal_min_CAD defined!
2012-10-05 17:00:21,093 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#5[192.168.20.71:56647])  no service_config parameter wallet_bal_min_CAD defined!
2012-10-05 17:01:10,444 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#5[192.168.20.71:56647])  no service_config parameter wallet_bal_min_CAD defined!
2012-10-05 17:01:47,704 ERROR [com.riavera.ejb.session.PurchasingBean] (WorkerThread#8[192.168.20.71:63593]) ::nnapp_fi_in::2144: unsupported address field 'cust_name' in address set
2012-10-05 17:03:47,473 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#0[192.168.20.71:14564])  no service_config parameter wallet_bal_min_CAD defined!
012-10-05 17:14:33,154 ERROR [com.riavera.ejb.session.PurchasingBean] (WorkerThread#10[192.168.20.71:57185]) ::nnapp_fi_in::2187: unsupported address field 'cust_name' in address set
2012-10-05 17:54:03,304 ERROR [org.jboss.ejb.plugins.LogInterceptor] (WorkerThread#3[192.168.20.71:52837])  TransactionRolledbackException in method: public abstract javax.ejb.EJBObject javax.ejb.Handle.getEJBObject() throws java.rmi.RemoteException, causedBy:: java.rmi.NoSuchObjectException: Could not activate; failed to restore state
	at org.jboss.ejb.plugins.AbstractInstanceCache.get(AbstractInstanceCache.java:134) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer.getEJBObject(StatefulSessionContainer.java:394) [:6.1.0.Final]
	at sun.reflect.GeneratedMethodAccessor3683.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at org.jboss.invocation.Invocation.performCall(Invocation.java:386) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer$ContainerInterceptor.invokeHome(StatefulSessionContainer.java:564) [:6.1.0.Final]
2012-10-05 18:12:52,217 ERROR [com.riavera.ejb.session.PurchasingBean] (WorkerThread#9[192.168.20.71:49147]) ::nnapp_fi_in::2202: unsupported address field 'cust_name' in address set
2012-10-05 18:12:52,314 WARN  [org.jboss.ejb3.interceptors.registry.InterceptorRegistry] (WorkerThread#3[192.168.20.71:9285]) ::nnapp_fi_in::2203: applicable interceptors is non-existent for public abstract boolean javax.ejb.EJBLocalObject.isIdentical(javax.ejb.EJBLocalObject) throws javax.ejb.EJBException
2012-10-05 18:12:52,534 INFO  [com.riavera.app.service.creditcard.hostedpci.WCreditCardHostedPci] (WorkerThread#3[192.168.20.71:9285]) ::nnapp_fi_in::2203: request failed - status: error/null
2012-10-05 18:12:52,535 INFO  [com.riavera.ejb.session.CreditCardBean] (WorkerThread#3[192.168.20.71:9285]) ::nnapp_fi_in::2203: got response from FI processor for ledger M176J: ERROR
2012-10-05 18:12:52,537 INFO  [com.navahonetworks.ejb.session.LedgerLogicBean] (WorkerThread#3[192.168.20.71:9285]) ::nnapp_fi_in::2203: release ledger on tx: M176J, paymentStatus: FAIL, responseCode: ERROR
2012-10-05 18:12:52,623 INFO  [com.navahonetworks.ejb.session.LedgerLogicBean] (WorkerThread#3[192.168.20.71:9285]) ::nnapp_fi_in::2203: ledger was rejected by FI: ERROR
2012-10-05 18:12:52,647 WARN  [com.navahonetworks.ejb.session.TransactionLogicBean] (WorkerThread#3[192.168.20.71:9285]) ::nnapp_fi_in::2203: deposit ledger (M176J) failed - cannot complete purchase
2012-10-05 18:25:00,031 ERROR [EJBVelocity] (Thread-16927) ::nobody::2209: ResourceManager : unable to find resource '/email/email_cust_deposit_release_en.vm' in any resource loader.
2012-10-05 18:25:00,031 ERROR [com.riavera.app.service.template.WTemplate] (Thread-16927) ::nobody::2209: cannot locate template '/email/email_cust_deposit_release_en.vm' - velocity exception: Unable to find resource '/email/email_cust_deposit_release_en.vm'
2012-10-05 18:25:00,031 ERROR [com.riavera.ejb.session.EventDispatcherBean] (Thread-16927) ::nobody::2209: exception handling queued event 26F1A4BDC0A8144733D0D500AAB0B7CB - will retry again later: com.riavera.exceptions.WNotFoundException: TEMPLATE_NOT_FOUND (9501): Cannot locate template
	at com.riavera.app.service.template.WTemplate.processTemplateToFile(WTemplate.java:358) [:]
	at sun.reflect.GeneratedMethodAccessor4552.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:157) [:6.0.0.GA]
	at org.jboss.mx.server.Invocation.dispatch(Invocation.java:96) [:6.0.0.GA]
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:88) [:6.0.0.GA]
2012-10-05 20:40:12,414 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#3[192.168.20.71:38761]) :miiscan-prod:38.104.209.14:druid0101@gmail.com::::0:  unable to find cust user:druid0101@gmail.comNo such entity!
2012-10-05 21:32:52,320 ERROR [org.jboss.ejb.plugins.LogInterceptor] (WorkerThread#5[192.168.20.71:58792])  TransactionRolledbackException in method: public abstract javax.ejb.EJBObject javax.ejb.Handle.getEJBObject() throws java.rmi.RemoteException, causedBy:: java.rmi.NoSuchObjectException: Could not activate; failed to restore state
	at org.jboss.ejb.plugins.AbstractInstanceCache.get(AbstractInstanceCache.java:134) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer.getEJBObject(StatefulSessionContainer.java:394) [:6.1.0.Final]
	at sun.reflect.GeneratedMethodAccessor3683.invoke(Unknown Source) [:1.6.0_33]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) [:1.6.0_33]
	at java.lang.reflect.Method.invoke(Method.java:597) [:1.6.0_33]
	at org.jboss.invocation.Invocation.performCall(Invocation.java:386) [:6.1.0.Final]
	at org.jboss.ejb.StatefulSessionContainer$ContainerInterceptor.invokeHome(StatefulSessionContainer.java:564) [:6.1.0.Final]
2012-10-05 21:33:00,062 ERROR [com.navahonetworks.ejb.session.app.CoreAppUseBean] (WorkerThread#5[192.168.20.71:58792]) :miiscan-prod:127.0.0.1:nnapp_core900::::0:  service config: fraud_rating_reg_system_handle_PH default value set - PLEASE FIX!
2012-10-05 23:05:17,274 ERROR [com.navahonetworks.ejb.session.app.LoginUserLogicBean] (WorkerThread#3[192.168.20.71:16871]) :MIISCAN:127.0.0.1:farley::M4H1J6::0:  unable to find cust user:farleyNo such entity!
